E-Ticaret/Controllers/AdminProductController.cs
using BusinessLayer.Concrate;
using DataAccesLayer.Context;
using EntityLayer.Entites;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace E_Ticaret.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminProductController : Controller
    {
        ProductRepository productRepository = new ProductRepository();
        DataContext db = new DataContext();
        public ActionResult Index(int sayfa=1)
        {
            return View(productRepository.List().ToPagedList(sayfa,3));
        }

        public ActionResult Create() 
        {
            List<SelectListItem> deger1 = (from i in db.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name,
                                               Value = i.Id.ToString(),


                                           }).ToList();
            ViewBag.ktgr = deger1;
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(Product data, HttpPostedFileBase File) 
        {
            if (!ModelState.IsValid) 
            {
                ModelState.AddModelError("", "Hata oluştu");
            }

            string path = Path.Combine("~/Content/Image/" + File.FileName);
            File.SaveAs(Server.MapPath(path));
            data.Image = File.FileName.ToString();
            productRepository.Insert(data);
            return RedirectToAction("Index");


        }

        public  ActionResult Delete(int id)
        {
            var delete = productRepository.GetById(id);
            productRepository.Delete(delete);
            return RedirectToAction("Index");

        }

        public ActionResult Update(int id) 
        {
            List<SelectListItem> deger1 = (from i in db.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name,
                                               Value = i.Id.ToString(),


                                           }).ToList();
            ViewBag.ktgr = deger1;
            var update = productRepository.GetById(id);
            return View(update);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Update(Product data, HttpPostedFileBase File)
        {
            var update = productRepository.GetById(data.Id);

            if (!ModelState.IsValid) 
            {
                if (File == null)
                {

                    update.Description = data.Description;
                    update.Name = data.Name;
                    update.IsApproved = data.IsApproved;
                    update.Popular = data.Popular;
                    update.Price = data.Price;
                    update.Stock = data.Stock;
                    update.CategoryId = data.CategoryId;
                    productRepository.Update(data);
                    return RedirectToAction("Index");
                }
                else
                {

                    update.Description = data.Description;
                    update.Name = data.Name;
                    update.IsApproved = data.IsApproved;
                    update.Popular = data.Popular;
                    update.Price = data.Price;
                    update.Stock = data.Stock;
                    update.Image = File.FileName.ToString();
                    update.CategoryId = data.CategoryId;
                    productRepository.Update(update);
                    return RedirectToAction("Index");
                }
            }
            
            return View(update);
        }
        public ActionResult CriticalStock() 
        {
            var kritik = db.Products.Where(x => x.Stock <= 50).ToList();
            return View(kritik);
        }

        public PartialViewResult StockCount()
        {
            if (User.Identity.IsAuthenticated)
            {
                var count = db.Products.Where(x => x.Stock < 50).Count();
                ViewBag.count = count;
                var azalan = db.Products.Where(x =>x.Stock == 50).Count();
                ViewBag.azalan = azalan;
            }
            return PartialView();
        }
    }
}

E-Ticaret/Views/AdminProduct/Create.cshtml
@model EntityLayer.Entites.Product
@{
    ViewBag.Title = "Create";
}



<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "btn btn-danger" })

                <div class="form-group">
                    <label>Ad</label>
                    <input type="text" class="form-control" name="Name" />
                    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Açıklama</label>
                    <input type="text" class="form-control" name="Description" />
                    @Html.ValidationMessageFor(x => x.Description, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Resim</label>
                    <input type="file" class="form-control" name= "File" />
                    @Html.ValidationMessageFor(x => x.Image, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Fiyat</label>
                    <input type="text" class="form-control" name="Price" />
                    @Html.ValidationMessageFor(x => x.Price, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Stok</label>
                    <input type="text" class="form-control" name="Stock" />
                    @Html.ValidationMessageFor(x => x.Stock, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Popüler</label>
                    @Html.EditorFor(x => x.Popular)
                    @Html.ValidationMessageFor(x => x.Popular, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Onay</label>
                    @Html.EditorFor(x => x.IsApproved)
                    @Html.ValidationMessageFor(x => x.IsApproved, "", new { @style = "color:red" })
                </div>
                <br />

                <div class="form-group">
                    <label>Kategori</label>
                    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.ktgr, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CategoryId, "", new { @style = "color:red" })
                </div>
                <button class="btn btn-primary" type="submit">Ekle</button>
                <a href="/AdminProduct/Index" class="btn btn-primary">Ürün Listesi</a>
            </form>
        </div>
    </div>
</div>

E-Ticaret/Views/AdminProduct/CriticalStock.cshtml
@model List<EntityLayer.Entites.Product>
@{
    ViewBag.Title = "CriticalStock";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Ürün Bilgisi</th>
        <th>Stok Sayısı</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.Stock < 50)
        {
            <tr style="background-color:red">
                <td>@item.Name</td>
                <td>@item.Stock</td>
            </tr>
        }
        if (item.Stock == 50)
        {
            <tr style="background-color:yellow">
                <td>@item.Name</td>
                <td>@item.Stock</td>
            </tr>
        }
    }
</table>

E-Ticaret/Views/AdminProduct/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EntityLayer.Entites.Product>
@{
    ViewBag.Title = "Index";
}

<a href="/AdminProduct/Create" class="btn btn-primary">Ekle</a>
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>Ad</th>
        <th>Açıklama</th>
        <th>Fiyat</th>
        <th>Stok</th>
        <th>Popüler</th>
        <th>Onay</th>
        <th>Resim</th>
        <th>Kategori</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td>
                @if (item.Popular == true)
                {
                    <lable class="btn btn-success">Evet</lable>
                }
                else
                {
                    <label class="btn btn-danger">Hayır</label>
                }
            </td>

            <td>
                @if (item.IsApproved == true)
                {
                    <label class="btn btn-success">Evet</label>
                }
                else
                {
                    <label class="btn btn-danger">Hayır</label>
                }
            </td>

            <td><img src="~/Content/Image/@item.Image" width="80" height="80" />Resim</td>

            <td>@item.Category.Name</td>

            <td>@Html.ActionLink("Sil", "Delete", new { item.Id }, new { @class = "btn btn-danger", onclick = "return confirm ('Silmek istiyor musunuz?')" })</td>

            <td><a class="btn btn-primary" href="@Url.Action("Update", "AdminProduct", new { id = item.Id })">Güncelle</a></td>
        </tr>
    }
</table>

@Html.PagedListPager(Model,sayfa=>Url.Action("Index",new {sayfa}),PagedListRenderOptions.Classic)

E-Ticaret/Views/AdminProduct/StockCount.cshtml
<lable style="color:red">@ViewBag.count</lable> <lable style="color:yellow">@ViewBag.azalan</lable>

E-Ticaret/Views/AdminProduct/Update.cshtml
@model EntityLayer.Entites.Product
@{
    ViewBag.Title = "Update";
}



<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "btn btn-danger" })

                <div class="form-group">
                    <label>Ad</label>
                    <input type="text" class="form-control" name="Name" value="@Model.Name" />
                    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Açıklama</label>
                    <input type="text" class="form-control" name="Description" value="@Model.Description" />
                </div>
                <br />
                <div class="form-group">
                    <label>Önceki Resim</label>
                    <img src="~/Content/Image/@Model.Image" width="80" height="80" />
                </div>
                <div class="form-group">
                    <label>Resim</label>
                    <input type="file" class="form-control" name="File" />
                </div>
                <br />
                <div class="form-group">
                    <label>Fiyat</label>
                    <input type="text" class="form-control" name="Price" value="@Model.Price" />
                </div>
                <br />
                <div class="form-group">
                    <label>Stok</label>
                    <input type="text" class="form-control" name="Stock" value="@Model.Stock" />
                </div>
                <br />
                <div class="form-group">
                    <label>Popüler</label>
                    @Html.EditorFor(x => x.Popular)
                </div>
                <br />
                <div class="form-group">
                    <label>Onay</label>
                    @Html.EditorFor(x => x.IsApproved)
                </div>
                <br />

                <div class="form-group">
                    <label>Kategori</label>
                    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.ktgr, new { @class = "form-control" })
                </div>
                <button class="btn btn-primary" type="submit">Ekle</button>
                <a href="/AdminProduct/Index" class="btn btn-primary">Ürün Listesi</a>
            </form>
        </div>
    </div>
</div>