E-Ticaret/Controllers/SalesController.cs
using DataAccesLayer.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using EntityLayer.Entites;

namespace E_Ticaret.Controllers
{
    public class SalesController : Controller
    {
        DataContext db = new DataContext();
        public ActionResult Index(int sayfa =1)
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciadi = User.Identity.Name;
                var kullanici = db.Users.FirstOrDefault(x=>x.Email == kullaniciadi);
                var model = db.Sales.Where(x => x.UserId == kullanici.Id).ToList().ToPagedList(sayfa,5);
                return View(model);
            }
            return HttpNotFound();
        }

        public ActionResult Buy(int id) 
        {
            var model = db.Carts.FirstOrDefault(x => x.Id == id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Buy2(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var model = db.Carts.FirstOrDefault(x => x.Id == id);
                    var satis = new Sales
                    {
                        UserId = model.UserId,
                        ProductId = model.ProductID,
                        Quantity = model.Quantity,
                        Image = model.Image,
                        Price = model.Price,
                        Date = DateTime.Now,
                    };

                    db.Carts.Remove(model);
                    db.Sales.Add(satis);
                    db.SaveChanges();
                    ViewBag.İslem = "Satın alma işlemi başarılı bir şekilde gerçekleşmiştir";
                }
            }
            catch (Exception)
            {

                ViewBag.İslem = "Satın alma işlemi başarısız";
            }

            return View("islem");
        }

        public ActionResult BuyAll(decimal? Tutar) 
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciadi = User.Identity.Name;
                var kullanici = db.Users.FirstOrDefault(x=>x.Email == kullaniciadi);
                var model = db.Carts.Where(x=>x.UserId == kullanici.Id).ToList();
                var kid = db.Carts.FirstOrDefault(x=>x.UserId == kullanici.Id);
                if (model != null) 
                {
                    if (kid == null) 
                    {
                        ViewBag.tutar = "Sepetinizde ürün bulunmamaktadır";
                    }
                    else if (kid != null) 
                    {
                        Tutar = db.Carts.Where(x => x.UserId == kid.UserId).Sum(x => x.Product.Price * x.Quantity);
                        ViewBag.tutar = "Toplam Tutar =" + Tutar + "$";
                        
                    }
                    return View(model);
                }
                return View();

            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult BuyAll2() 
        {
            var username = User.Identity.Name;
            var kullanici =db.Users.FirstOrDefault(x=>x.Email == username);
            var model = db.Carts.Where(x=>x.UserId == kullanici.Id).ToList();
            int row = 0;
            foreach (var item in model)
            {
                var satis = new Sales
                {
                    UserId = model[row].UserId,
                    ProductId = model[row].ProductID,
                    Quantity = model[row].Quantity,
                    Image = model[row].Image,
                    Date = DateTime.Now
                };
                db.Sales.Add(satis);
                db.SaveChanges();
                row++;
            }
            db.Carts.RemoveRange(model);
            db.SaveChanges();
            return RedirectToAction("Index","Cart");
        }
    }
}

E-Ticaret/Views/Sales/Buy.cshtml
@model EntityLayer.Entites.Cart
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Bıçakçıoğlu knife/css/style.css">

<div class="banner_section layout_padding">
    <div class="container">
        <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Hayalindeki <br>Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Özel Çelikten <br>Yapılmış Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Kişiye<br>Özel Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>
</div>
   </div>

<div class="container">
    <div class="modal-header">
        <h2>Satın Al</h2>
    </div>

    <div class="container">
        @using (Html.BeginForm("Buy2", "Sales", FormMethod.Post))
        {
            <div class="modal-body">
                @Html.HiddenFor(x => x.Id)

                <div class="form-group">
                    Kullanıcı Adı Soyadı: @Session["Ad"] @Session["Soyad"]
                </div>

                <div class="form-group">
                    Ürün Bilgisi: @Html.DisplayFor(x => x.Product.Name, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    Adet: @Html.DisplayFor(x => x.Quantity, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <img src="~/Content/Image/@Model.Product.Image" width="200" height="200" />
                </div>

                <div class="form-group">
                    Fiyat: @Html.DisplayFor(x => x.Price, new { @class = "form-control" })
                </div>
            </div>

            <div class="modal-footer" style="float:right">
                <button class="btn btn-success">Satın Al</button>
                <a href="/Cart/Index" class="btn btn-danger">İptal</a>
            </div>
        }
    </div>
</div>    

E-Ticaret/Views/Sales/BuyAll.cshtml
@model List<EntityLayer.Entites.Cart>
@{
    ViewBag.Title = "BuyAll";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<div class="banner_section layout_padding">
    <div class="container">
        <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Hayalindeki <br>Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Özel Çelikten <br>Yapılmış Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Kişiye<br>Özel Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>
</div>
   </div>

<div class="container">
    <div class="container">
        <div class="row">
            <h2>Merhaba @Session["Ad"]  @Session["Soyad"] Satın Alma işlemini tamamlayın.</h2>
        </div>

        <div class="container">
            @using (Html.BeginForm("BuyAll2", "Sales", FormMethod.Post, new { @class = "container" }))
            {
                foreach (var item in Model)
                {
                    <div class="form-group">
                        <h4> ID: @Html.DisplayFor(x => item.Id)</h4>
                    </div>

                    <div class="form-group">
                        <h4> Ürün Ad: @Html.DisplayFor(x => item.Product.Name)</h4>
                    </div>

                    <div class="form-group">
                        <h4> Adet: @Html.DisplayFor(x => item.Quantity)</h4>
                    </div>

                    <div class="form-group">
                        <h4> Fiyat: @Html.DisplayFor(x => item.Price)</h4>
                    </div>

                    <div class="form-group">
                        <h5> Resim: <img src="~/Content/Image/@item.Product.Image" width="200" height="200" /></h5>
                    </div>



                }
                <p style="color:red; text-align:center">@ViewBag.Tutar</p>
                <div class="container">
                    <div class="form-group" style="float:left">
                        <button class="btn btn-success">Onay</button>
                    </div>

                    <div style="float:right">
                        <a href="/Cart/Index" class="btn btn-danger">İptal</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

E-Ticaret/Views/Sales/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EntityLayer.Entites.Sales>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="banner_section layout_padding">
    <div class="container">
        <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Hayalindeki <br>Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Özel Çelikten <br>Yapılmış Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-sm-12">
                            <h1 class="banner_taital">Kişiye<br>Özel Bıçaklar bu sayfada</h1>
                            <div class="buynow_bt"><a href="#">Satın Al</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>
</div>
  </div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Satış Listesi</h2>
            <table class="table table-bordered">
                <tr>
                    <th>Id</th>
                    <th>Ürün Ad</th>
                    <th>Adet</th>
                    <th>Fiyat</th>
                    <th>Resim</th>
                    <th>Tarih</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Product.Name</td>
                            <td>@item.Quantity</td>
                            <td>@item.Price</td>
                            <td><img src="~/Content/Image/@item.Product.Image" width="200" height="200" /></td>
                            <td>@Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy")</td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
        @Html.PagedListPager(Model, sayfa => Url.Action("Index", new { sayfa }), PagedListRenderOptions.Classic)
    </div>
 </div>

            

E-Ticaret/Views/Sales/islem.cshtml
@{
    ViewBag.Title = "islem";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<!DOCTYPE html>
<html lang="Tr">
<head>
    <link href="~/Bıçakçıoğlu knife/css/style.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_section layout_padding">
        <div class="container">
            <div id="my_slider" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="row">
                            <div class="col-sm-12">
                                <h1 class="banner_taital">Hayalindeki <br>Bıçaklar bu sayfada</h1>
                                <div class="buynow_bt"><a href="#">Satın Al</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-sm-12">
                                <h1 class="banner_taital">Özel Çelikten <br>Yapılmış Bıçaklar bu sayfada</h1>
                                <div class="buynow_bt"><a href="#">Satın Al</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-sm-12">
                                <h1 class="banner_taital">Kişiye<br>Özel Bıçaklar bu sayfada</h1>
                                <div class="buynow_bt"><a href="#">Satın Al</a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                    <i class="fa fa-angle-left"></i>
                </a>
                <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>
        </div>
    </div>
    </div>

    <div class="container">
        <div class="row">
            <h1>@ViewBag.İslem</h1>
        </div>
    </div>
</body>
</html>