E-Ticaret/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrate;
using EntityLayer.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Ticaret.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminCategoryController : Controller
    {
        CategoryRepository categoryRepository= new CategoryRepository();
        public ActionResult Index()
        {
            return View(categoryRepository.List());
        }

        public ActionResult Create()
        {
            return View();
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(Category p)
        {
            if (ModelState.IsValid)
            {
                categoryRepository.Insert(p);

                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Bir Hata oluştu");
            return View();
        }

        public ActionResult Delete(int id)
        {
            var delete = categoryRepository.GetById(id);
            categoryRepository.Delete(delete);
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id) 
        {
            var update = categoryRepository.GetById(id);    
            return View(update);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Update(Category p)
        {
            if (ModelState.IsValid)
            {
                var update = categoryRepository.GetById(p.Id);
                update.Name = p.Name;
                update.Description = p.Description;
                categoryRepository.Update(update);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Bir Hata oluştu");
            return View();

        }
    }
}

E-Ticaret/Views/AdminCategory/Create.cshtml
@model EntityLayer.Entites.Category
@{
    ViewBag.Title = "Create";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "btn btn-danger" })

                <div class="form-group">
                    <label>Ad</label>
                    <input type="text" class="form-control" name="Name" />
                    @Html.ValidationMessageFor(x=>x.Name, "",new {@style ="color:red"})
                </div>
                <br />
                <div class="form-group">
                    <label>Açıklama</label>
                    <input type="text" class="form-control" name="Description" />
                    @Html.ValidationMessageFor(x => x.Description, "", new { @style = "color:red" })
                </div>
                <br />
                <button class="btn btn-primary" type="submit">Ekle</button>
            </form>
        </div>
    </div>
</div>

E-Ticaret/Views/AdminCategory/Index.cshtml
@model List<EntityLayer.Entites.Category>
@{
    ViewBag.Title = "Index";
}

<a class="btn btn-primary" href="/AdminCategory/Create">Kategori Ekle</a>
<br /> 
<br />
<table class="table table-bordered" id="table">
    <tr>
        <th>Ad</th>
        <th>Açıklama</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Description</td>
            @*<td>@Html.ActionLink("Sil","Delete",new {item.Id}, new {@class="btn btn-danger", onclick="return confirm ('Silmek istiyor musunuz?')"})</td>*@
            <td><a class="btn btn-danger btnSil" data-id="@item.Id">Sil</a></td>
            <td><a class="btn btn-primary" href="@Url.Action("Update", "AdminCategory", new { id = item.Id })">Güncelle</a></td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-3.7.0.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#table").on("click", ".btnSil", function () {

            var btn = $(this);
            bootbox.confirm("Silmek istediğinize emin misiniz ?", function (result) {

                if (result) {
                    var id = btn.data("id");

                    $.ajax({
                        type: "GET",
                        URL: "/AdminCategory/Delete/" + id,
                        success: function () {
                            btn.parent().parent().remove();
                        }
                    });
                } else {
                    bootbox.confirm("Hata oluştu");
                }

            })

        });
    });
</script>

E-Ticaret/Views/AdminCategory/Update.cshtml
@model EntityLayer.Entites.Category
@{
    ViewBag.Title = "Update";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "btn btn-danger" })

                <div class="form-group">
                    <label>Ad</label>
                    <input type="text" class="form-control" name="Name" value="@Model.Name" />
                    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
                </div>
                <br />
                <div class="form-group">
                    <label>Açıklama</label>
                    <input type="text" class="form-control" name="Description" value="@Model.Description" />
                    @Html.ValidationMessageFor(x => x.Description, "", new { @style = "color:red" })
                </div>
                <br />
                <button class="btn btn-primary" type="submit">Güncelle</button>
            </form>
        </div>
    </div>
</div>